version: '3.3'
services:
  jenkins-a:
    image: jenkins/jenkins:2.89
    ports:
      - "7088:8080"
      - "50001:50000"
    volumes:
      - ~/jenkins-standby:/var/jenkins_home
    restart: always
  jenkins-b:
    image: jenkins/jenkins:2.89
    ports:
      - "7089:8080"
      - "50002:50000"
    volumes:
      - ~/jenkins-standby:/var/jenkins_home
    restart: always
volumes:
    db_data: {}